### ISSUE TITLE
dbcat - NetBSD package

### ISSUE THREAD

**Issue by 0323pin** [NishantJoshi00/dbcat#1]
Hi,

I've just packaged `dbcat` for NetBSD and would like to ask if it's possible to provide github tags in sync with releases in crates.io?
It would make package maintenance significantly easier.

Thanks.
The package hasn't been merged yet but, I intend to do it later today or tomorrow.

**Comment by NishantJoshi00** [comment]
Sure, I was figuring out an efficient way to do this with GitHub actions. I'll try to get it done by today

**Comment by 0323pin** [comment]
Cheers.
A version tag is sufficient.

**Comment by 0323pin** [comment]
@NishantJoshi00 Thanks, merged into the main branch now, https://mail-index.netbsd.org/pkgsrc-changes/2022/02/09/msg248349.html

###To install on NetBSD run,

```sh
pkgin install dbcat
```

or, if you prefer to build from source,

```sh
cd /usr/pkgsrc/textproc/dbcat
make install
```
